# -*- coding: utf-8 -*-
"""SHM_Crack_Detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5Jj0C_DdGLSQ4q1Z2KMpQMNspV301OP
"""

#  CONCRETE CRACK DETECTION BINARY CLASSIFIER
# A very efficint program

import os
import shutil
import random
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# InstallING and importing patool to handle .rar files
!pip install patool -q
import patoolib

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models
from sklearn.metrics import classification_report
from google.colab import drive, files

# STEP 1: MOUNING GOOGLE DRIVE
drive.mount('/content/drive')

# STEP 2: SETTINGS & PATHS
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DRIVE_PATH = '/content/drive/MyDrive/data.zip.rar'
LOCAL_RAR = 'data.zip.rar'
RAW_DATA_DIR = "raw_data"
DATASET_DIR = "dataset"

# Labeling: Positive = Crack, Negative = No Crack
CLASS_NAMES = ["Crack", "No Crack"]
NUM_EPOCHS = 5

print(f"[INFO] Using device: {DEVICE}")

# STEP 3: COPYING & EXTRACTING FROM DRIVE
if os.path.exists(DRIVE_PATH):
    if not os.path.exists(LOCAL_RAR):
        print("[INFO] Copying file from Google Drive...")
        shutil.copy(DRIVE_PATH, LOCAL_RAR)

    if os.path.exists(RAW_DATA_DIR):
        shutil.rmtree(RAW_DATA_DIR)
    os.makedirs(RAW_DATA_DIR, exist_ok=True)

    print(f"[INFO] Extracting {LOCAL_RAR}...")
    patoolib.extract_archive(LOCAL_RAR, outdir=RAW_DATA_DIR, verbosity=-1)
else:
    print(f"ERROR: '{DRIVE_PATH}' not found in Drive.")

# STEP 4: FINDING FOLDERS & SPLITING (80/20) - for training and Validation
def find_true_source(root_dir):
    for root, dirs, files in os.walk(root_dir):
        # We look for the original dataset folder names to split them
        if "Positive" in dirs and "Negative" in dirs:
            return root
    return None

if not os.path.exists(DATASET_DIR):
    true_root = find_true_source(RAW_DATA_DIR)
    if true_root:
        print(f"[INFO] Images found. Splitting into {CLASS_NAMES}...")
        # Maping original names (Positive/Negative) to our user-friendly names (Crack/No Crack)
        mapping = {"Positive": "Crack", "Negative": "No Crack"}
        for old_name, new_name in mapping.items():
            src = os.path.join(true_root, old_name)
            all_files = [f for f in os.listdir(src) if f.lower().endswith(('.jpg', '.png'))]
            random.seed(42)
            random.shuffle(all_files)

            split = int(len(all_files) * 0.8)
            for phase, f_list in [('train', all_files[:split]), ('val', all_files[split:])]:
                dest = os.path.join(DATASET_DIR, phase, new_name)
                os.makedirs(dest, exist_ok=True)
                for f in f_list:
                    shutil.copy(os.path.join(src, f), os.path.join(dest, f))
        print("[SUCCESS] Dataset created.")

# STEP 5: DATA LOADERS
train_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

val_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_ds = datasets.ImageFolder(os.path.join(DATASET_DIR, "train"), train_tf)
val_ds = datasets.ImageFolder(os.path.join(DATASET_DIR, "val"), val_tf)
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=32, shuffle=False)

# STEP 6: MODEL & TRAINING
model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)
model.fc = nn.Linear(model.fc.in_features, 2)
model = model.to(DEVICE)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

history = {'t_loss': [], 'v_loss': [], 't_acc': [], 'v_acc': []}

print(f"\n[INFO] Starting training...")
for epoch in range(NUM_EPOCHS):
    model.train()
    t_loss, t_corr = 0.0, 0
    for imgs, lbls in train_loader:
        imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
        optimizer.zero_grad()
        out = model(imgs)
        loss = criterion(out, lbls)
        loss.backward(); optimizer.step()
        t_loss += loss.item() * imgs.size(0)
        t_corr += torch.sum(out.argmax(1) == lbls)

    model.eval()
    v_loss, v_corr = 0.0, 0
    with torch.no_grad():
        for imgs, lbls in val_loader:
            imgs, lbls = imgs.to(DEVICE), lbls.to(DEVICE)
            out = model(imgs)
            v_loss += criterion(out, lbls).item() * imgs.size(0)
            v_corr += torch.sum(out.argmax(1) == lbls)

    history['t_loss'].append(t_loss/len(train_ds))
    history['v_loss'].append(v_loss/len(val_ds))
    history['t_acc'].append(t_corr.double().item()/len(train_ds))
    history['v_acc'].append(v_corr.double().item()/len(val_ds))
    print(f"Epoch {epoch+1} | Loss: {history['v_loss'][-1]:.4f} | Acc: {history['v_acc'][-1]:.4f}")

# STEP 7: GRAPHS & EVALUATION
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1); plt.plot(history['t_loss'], label='Train'); plt.plot(history['v_loss'], label='Val'); plt.title('Loss History'); plt.legend()
plt.subplot(1, 2, 2); plt.plot(history['t_acc'], label='Train'); plt.plot(history['v_acc'], label='Val'); plt.title('Accuracy History'); plt.legend()
plt.show()

print("\n--- PERFORMANCE REPORT ---")
y_true, y_pred = [], []
model.eval()
with torch.no_grad():
    for imgs, lbls in val_loader:
        out = model(imgs.to(DEVICE))
        y_true.extend(lbls.numpy()); y_pred.extend(out.argmax(1).cpu().numpy())
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES))

# STEP 8: SAVEING MODEL
model_save_path = '/content/drive/MyDrive/crack_detector_model.pth'
torch.save(model.state_dict(), model_save_path)
print(f"[INFO] Model weights saved to Drive.")
# For User image classifier (application)
def verify_and_display():
    print("\n--- CONCRETE SCANNER ---")
    print("Please upload an image of the concrete surface:")
    up = files.upload()

    model.eval() # Seting model to Evaluation mode

    for fn in up.keys():
        # Loading and processing image
        img = Image.open(fn).convert('RGB')
        img_t = val_tf(img).unsqueeze(0).to(DEVICE)

        with torch.no_grad():
            outputs = model(img_t)
            prob = torch.nn.functional.softmax(outputs, dim=1)
            confidence, predicted_idx = torch.max(prob, 1)

        # Determining user-friendly text and color
        raw_label = CLASS_NAMES[predicted_idx]
        if raw_label == "Crack":
            user_result = "CRACK DETECTED"
            result_color = "red"
        else:
            user_result = "NO CRACK DETECTED (Intact Surface)"
            result_color = "green"

        # Displaying Result
        plt.figure(figsize=(6, 6))
        plt.imshow(img)
        plt.title(f"{user_result}\nConfidence: {confidence.item()*100:.1f}%",
                  color=result_color, fontsize=14, fontweight='bold')
        plt.axis('off')
        plt.show()

# Running  the user-friendly verifier
verify_and_display()